Repository redacademy/bcf-fall-2019, pull requests merged in 2019-12, with the labels that each got.

#5 remove Post schema
  server/README.md
  server/prisma/datamodel.prisma
Labels: enhancement

#20 Add libraries for navigation and onboarding
  client/android/app/build.gradle
  client/android/app/src/main/java/com/bpfall2019/MainActivity.java
  client/index.js
  client/ios/Podfile.lock
  client/package.json
  client/yarn.lock
Labels: enhancement

#22 Add async-storage
  client/ios/Podfile.lock
  client/package.json
  client/yarn.lock
Labels: enhancement

#14 Update gitignore file
  .gitignore
  README.md
  client/ios/Podfile.lock
  server/.gitignore
Labels: enhancement

#4 Add readme.md
  .gitconfig
  README.md
Labels: documentation

#16 Create the file structure
  client/android/app/BUCK
  client/android/app/build.gradle
  client/android/app/src/main/AndroidManifest.xml
  client/android/app/src/main/java/com/bcparksfoundation/MainActivity.java
  client/android/app/src/main/java/com/bcparksfoundation/MainApplication.java
  client/android/app/src/main/res/values/strings.xml
  client/android/settings.gradle
  client/app.json
  client/index.js
  client/ios/BCParksFoundation-tvOS/Info.plist
  client/ios/BCParksFoundation-tvOSTests/Info.plist
  client/ios/BCParksFoundation.xcodeproj/project.pbxproj
  client/ios/BCParksFoundation.xcodeproj/xcshareddata/xcschemes/BCParksFoundation-tvOS.xcscheme
  client/ios/BCParksFoundation.xcodeproj/xcshareddata/xcschemes/BCParksFoundation.xcscheme
  client/ios/BCParksFoundation.xcworkspace/contents.xcworkspacedata
  client/ios/BCParksFoundation/AppDelegate.h
  client/ios/BCParksFoundation/AppDelegate.m
  client/ios/BCParksFoundation/Base.lproj/LaunchScreen.xib
  client/ios/BCParksFoundation/Images.xcassets/AppIcon.appiconset/Contents.json
  client/ios/BCParksFoundation/Images.xcassets/Contents.json
  client/ios/BCParksFoundation/Info.plist
  client/ios/BCParksFoundation/main.m
  client/ios/BCParksFoundationTests/BCParksFoundationTests.m
  client/ios/BCParksFoundationTests/Info.plist
  client/ios/Podfile
  client/js/App.js
  client/js/apollo/index.js
  client/js/assests/index.js
  client/js/components/index.js
  client/js/config/index.js
  client/js/context/index.js
  client/js/lib/index.js
  client/js/navigation/index.js
  client/js/screens/index.js
  client/package.json
Labels: enhancement

#25 Include dependencies related to Nagivation bars
  client/package.json
  client/yarn.lock
Labels: enhancement

#26 Create global styles
  client/android/app/src/main/assets/fonts/Montserrat-Regular.otf
  client/android/app/src/main/assets/fonts/Montserrat-SemiBold.otf
  client/ios/BCParksFoundation.xcodeproj/project.pbxproj
  client/ios/BCParksFoundation/Info.plist
  client/js/App.js
  client/js/assets/fonts/Montserrat-Regular.otf
  client/js/assets/fonts/Montserrat-SemiBold.otf
  client/js/assets/index.js
  client/js/config/Theme/index.js
  client/js/config/index.js
  client/react-native.config.js
Labels: enhancement

#28 Create Onboarding screens
  client/js/assets/images/imgOnboarding01.jpg
  client/js/assets/images/imgOnboarding01@2x.jpg
  client/js/assets/images/imgOnboarding01@3x.jpg
  client/js/assets/images/imgOnboarding02.jpg
  client/js/assets/images/imgOnboarding02@2x.jpg
  client/js/assets/images/imgOnboarding02@3x.jpg
  client/js/assets/images/imgOnboarding03.jpg
  client/js/assets/images/imgOnboarding03@2x.jpg
  client/js/assets/images/imgOnboarding03@3x.jpg
  client/js/config/Theme/index.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Onboarding/OnboardingContainer.js
  client/js/screens/Onboarding/index.js
  client/js/screens/Onboarding/styles.js
Labels: enhancement

#32 Af feature schema
  server/prisma/datamodel.prisma
Labels: enhancement

#33 Fix bugs in prisma schema
  server/prisma/datamodel.prisma
Labels: bug

#34 Af bugfix schema
  server/prisma/datamodel.prisma
  server/src/generated/prisma-client/index.d.ts
  server/src/generated/prisma-client/index.js
  server/src/generated/prisma-client/prisma-schema.js
  server/yarn.lock
Labels: bug

#31 Add React final form
  client/package.json
  client/yarn.lock
Labels: enhancement

#37 resolve auth bug
  server/src/generated/prisma-client/index.d.ts
  server/src/generated/prisma-client/prisma-schema.js
  server/src/schema.graphql
  server/src/utils.js
Labels: bug

#38 Install react-navigation-drawer
  client/package.json
  client/yarn.lock
Labels: enhancement

#39 Add react-native-checkbox
  client/package.json
  client/yarn.lock
Labels: enhancement

#40 Remove react-native-checkbox
  client/package.json
  client/yarn.lock
Labels: enhancement

#42 Af bugfix schema2
  server/prisma/datamodel.prisma
  server/prisma/seed.graphql
Labels: bug

#46 Install Apollo client dependencies
  client/package.json
  client/yarn.lock
Labels: enhancement

#44 Create the onboarding screen
  client/ios/BCParksFoundation.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  client/js/App.js
  client/js/assets/images/icCheckboxDefault.png
  client/js/assets/images/icCheckboxDefault@2x.png
  client/js/assets/images/icCheckboxDefault@3x.png
  client/js/assets/images/icCheckboxSelected.png
  client/js/assets/images/icCheckboxSelected@2x.png
  client/js/assets/images/icCheckboxSelected@3x.png
  client/js/assets/images/icFacebook.png
  client/js/assets/images/icFacebook@2x.png
  client/js/assets/images/icFacebook@3x.png
  client/js/assets/images/icGoogle.png
  client/js/assets/images/icGoogle@2x.png
  client/js/assets/images/icGoogle@3x.png
  client/js/assets/images/icRadioDefault.png
  client/js/assets/images/icRadioDefault@2x.png
  client/js/assets/images/icRadioDefault@3x.png
  client/js/assets/images/icRadioSelected.png
  client/js/assets/images/icRadioSelected@2x.png
  client/js/assets/images/icRadioSelected@3x.png
  client/js/assets/images/imgSignIn01.jpg
  client/js/assets/images/imgSignIn01@2x.jpg
  client/js/assets/images/imgSignIn01@3x.jpg
  client/js/components/ButtonDefault/ButtonDefault.js
  client/js/components/ButtonDefault/index.js
  client/js/components/InputDefaultCheckBox/InputDefaultCheckBox.js
  client/js/components/InputDefaultCheckBox/index.js
  client/js/components/InputDefaultCheckBox/styles.js
  client/js/components/InputDefaultField/InputDefaultField.js
  client/js/components/InputDefaultField/index.js
  client/js/components/InputDefaultField/styles.js
  client/js/components/TitleText/TitleText.js
  client/js/components/TitleText/index.js
  client/js/components/TitleText/styles.js
  client/js/config/Theme/index.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignIn/SignInContainer.js
  client/js/screens/SignIn/index.js
  client/js/screens/SignIn/styles.js
Labels: enhancement

#47 Change Audio schema to comply with designers request
  server/prisma/datamodel.prisma
Labels: enhancement

#49 Install prop-types
  client/package.json
Labels: enhancement

#51 Af bugfix audioschema
  server/prisma/datamodel.prisma
Labels: bug

#50 Af feature asyncstorage
  client/js/config/models.js
Labels: enhancement

#54 Af bugfix schemaaudio2
  server/prisma/datamodel.prisma
Labels: bug

#66 Install image-picker and scree-blur dependencies
  client/ios/Podfile.lock
  client/package.json
  client/yarn.lock
Labels: enhancement

#55 Add logic for login and watching onboarding for the first time
  client/js/App.js
  client/js/apollo/index.js
  client/js/apollo/mutations.js
  client/js/components/ButtonDefault/ButtonDefault.js
  client/js/components/InputDefaultCheckBox/InputDefaultCheckBox.js
  client/js/components/InputDefaultField/InputDefaultField.js
  client/js/components/TitleText/TitleText.js
  client/js/config/api.js
  client/js/config/models.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/AuthLoading/AuthLoading.js
  client/js/screens/AuthLoading/AuthLoadingContainer.js
  client/js/screens/AuthLoading/index.js
  client/js/screens/AuthLoading/styles.js
  client/js/screens/Home/Home.js
  client/js/screens/Home/HomeContainer.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Onboarding/OnboardingContainer.js
  client/js/screens/Onboarding/styles.js
  client/js/screens/ServiceLoading/ServiceLoading.js
  client/js/screens/ServiceLoading/ServiceLoadingContainer.js
  client/js/screens/ServiceLoading/index.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignIn/SignInContainer.js
  client/js/screens/SignIn/styles.js
  client/js/screens/index.js
Labels: enhancement

#67 Install react-native-streaming-audio-player
  client/package.json
  client/yarn.lock
Labels: enhancement

#68 Af feature selfguidedschema
  client/ios/Podfile.lock
  client/js/screens/Booking/Booking.js
  server/prisma/datamodel.prisma
Labels: enhancement

#70 Install react-navigation-collapsible
  client/package.json
  client/yarn.lock
Labels: enhancement

#71 Add sign up logic
  client/ios/Podfile.lock
  client/js/components/CityPicker/CityPicker.js
  client/js/components/CityPicker/index.js
  client/js/components/CityPicker/styles.js
  client/js/components/ModalOverlay/ModalOverlay.js
  client/js/components/ModalOverlay/index.js
  client/js/components/ModalOverlay/styles.js
  client/js/config/Theme/index.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignUp/SignUp.js
  client/js/screens/SignUp/SignUpContainer.js
  client/js/screens/SignUp/styles.js
Labels: enhancement

#52 Infomodal
  client/ios/Podfile
  client/ios/Podfile.lock
  client/js/apollo/queries.js
  client/js/assets/images/icCloseWhite.png
  client/js/assets/images/icCloseWhite@2x.png
  client/js/assets/images/icCloseWhite@3x.png
  client/js/assets/images/icMenuWhite.png
  client/js/assets/images/icMenuWhite@2x.png
  client/js/assets/images/icMenuWhite@3x.png
  client/js/assets/images/icMinusDefault.png
  client/js/assets/images/icMinusDefault@2x.png
  client/js/assets/images/icMinusDefault@3x.png
  client/js/assets/images/icPlusDefault.png
  client/js/assets/images/icPlusDefault@2x.png
  client/js/assets/images/icPlusDefault@3x.png
  client/js/assets/images/icSocialFacebook.png
  client/js/assets/images/icSocialFacebook@2x.png
  client/js/assets/images/icSocialFacebook@3x.png
  client/js/assets/images/icSocialInstagram.png
  client/js/assets/images/icSocialInstagram@2x.png
  client/js/assets/images/icSocialInstagram@3x.png
  client/js/assets/images/icSocialTwitter.png
  client/js/assets/images/icSocialTwitter@2x.png
  client/js/assets/images/icSocialTwitter@3x.png
  client/js/assets/images/imgAboutUsLogo.png
  client/js/assets/images/imgAboutUsLogo@2x.png
  client/js/assets/images/imgAboutUsLogo@3x.png
  client/js/components/FaqForum/FaqForum.js
  client/js/components/FaqForum/index.js
  client/js/components/FaqForum/styles.js
  client/js/components/Loader/Loader.js
  client/js/components/Loader/styles.js
  client/js/lib/dataFormatHelper.js
  client/js/navigation/DrawerNavigation.js
  client/js/navigation/DrawerScreen.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/navigation/config.js
  client/js/navigation/index.js
  client/js/screens/About/About.js
  client/js/screens/About/AboutContainer.js
  client/js/screens/About/styles.js
  client/js/screens/Contact/Contact.js
  client/js/screens/Contact/ContactContainer.js
  client/js/screens/Contact/styles.js
  client/js/screens/Faq/Faq.js
  client/js/screens/Faq/FaqContainer.js
  client/js/screens/Faq/styles.js
Labels: enhancement

#80 Install react-native-maps
  client/package.json
  client/yarn.lock
Labels: enhancement

#83 Update dependencies
  client/package.json
  client/yarn.lock
Labels: enhancement

#84 Install react-native-video
  client/ios/BCParksFoundation.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  client/ios/Podfile.lock
  client/package.json
  client/yarn.lock
Labels: enhancement

#86 Add design components for StoryTrail screen
  client/js/assets/images/imgBgSelfGuidedTourAudio.png
  client/js/assets/images/imgBgSelfGuidedTourAudio@2x.png
  client/js/assets/images/imgBgSelfGuidedTourAudio@3x.png
  client/js/assets/images/mediaControllers/icAudioBackward.png
  client/js/assets/images/mediaControllers/icAudioBackward@2x.png
  client/js/assets/images/mediaControllers/icAudioBackward@3x.png
  client/js/assets/images/mediaControllers/icAudioForward.png
  client/js/assets/images/mediaControllers/icAudioForward@2x.png
  client/js/assets/images/mediaControllers/icAudioForward@3x.png
  client/js/assets/images/mediaControllers/icAudioPause.png
  client/js/assets/images/mediaControllers/icAudioPause@2x.png
  client/js/assets/images/mediaControllers/icAudioPause@3x.png
  client/js/assets/images/mediaControllers/icAudioPlay.png
  client/js/assets/images/mediaControllers/icAudioPlay@2x.png
  client/js/assets/images/mediaControllers/icAudioPlay@3x.png
  client/js/assets/images/mediaControllers/icAudioPlaySmallActive.png
  client/js/assets/images/mediaControllers/icAudioPlaySmallActive@2x.png
  client/js/assets/images/mediaControllers/icAudioPlaySmallActive@3x.png
  client/js/assets/images/mediaControllers/icAudioPlaySmallDefault.png
  client/js/assets/images/mediaControllers/icAudioPlaySmallDefault@2x.png
  client/js/assets/images/mediaControllers/icAudioPlaySmallDefault@3x.png
  client/js/assets/images/mediaControllers/icAudioStop.png
  client/js/assets/images/mediaControllers/icAudioStop@2x.png
  client/js/assets/images/mediaControllers/icAudioStop@3x.png
  client/js/assets/images/mediaControllers/imgSlider.png
  client/js/assets/images/mediaControllers/imgSlider@2x.png
  client/js/assets/images/mediaControllers/imgSlider@3x.png
  client/js/components/AudioItem/AudioItem.js
  client/js/components/AudioItem/index.js
  client/js/components/AudioItem/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/SelfGuidedTour/SelfGuidedTourContainer.js
  client/js/screens/StoryTrail/StoryTrail.js
  client/js/screens/StoryTrail/StoryTrailContainer.js
  client/js/screens/StoryTrail/styles.js
Labels: enhancement

#88 Add audio functionality
  client/js/screens/StoryTrail/StoryTrail.js
  client/js/screens/StoryTrail/styles.js
Labels: enhancement

#90 Add a dynamic header feature
  client/js/screens/Home/Home.js
  client/js/screens/Home/HomeContainer.js
  client/js/screens/Home/styles.js
Labels: enhancement

#100 Install date picker
  client/ios/Podfile.lock
  client/package.json
  client/yarn.lock
Labels: enhancement

#103 Add reviews to schema table of self guided tours
  server/prisma/datamodel.prisma
Labels: enhancement

#92 Update navigation with minor changes
  client/js/assets/images/icMenuDefault.png
  client/js/assets/images/icMenuDefault@2x.png
  client/js/assets/images/icMenuDefault@3x.png
  client/js/context/index.js
  client/js/navigation/DrawerNavigation.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/navigation/config.js
  client/js/screens/StoryTrail/StoryTrail.js
  client/js/screens/StoryTrail/StoryTrailContainer.js
Labels: bug, enhancement

#99 Self Guided Screen
  client/ios/BCParksFoundation.xcodeproj/project.pbxproj
  client/js/apollo/queries.js
  client/js/assets/images/icChevronDownDefault.png
  client/js/assets/images/icChevronDownDefault@2x.png
  client/js/assets/images/icChevronDownDefault@3x.png
  client/js/assets/images/icFaveShareDefault.png
  client/js/assets/images/icFaveShareDefault@2x.png
  client/js/assets/images/icFaveShareDefault@3x.png
  client/js/assets/images/icFilterRemoveWhite.png
  client/js/assets/images/icFilterRemoveWhite@2x.png
  client/js/assets/images/icFilterRemoveWhite@3x.png
  client/js/assets/images/icHeadsetActive.png
  client/js/assets/images/icHeadsetActive@2x.png
  client/js/assets/images/icHeadsetActive@3x.png
  client/js/assets/images/icHeadsetDefault.png
  client/js/assets/images/icHeadsetDefault@2x.png
  client/js/assets/images/icHeadsetDefault@3x.png
  client/js/components/SelfGuidedItem/SelfGuidedItem.js
  client/js/components/SelfGuidedItem/index.js
  client/js/components/SelfGuidedItem/styles.js
  client/js/navigation/config.js
  client/js/screens/SelfGuidedTour/SelfGuidedTour.js
  client/js/screens/SelfGuidedTour/SelfGuidedTourContainer.js
  client/js/screens/SelfGuidedTour/index.js
  client/js/screens/SelfGuidedTour/styles.js
  client/package.json
Labels: enhancement

#105 Add event category filtering logic
  client/js/assets/images/icArrLeftWhite.png
  client/js/assets/images/icArrLeftWhite@2x.png
  client/js/assets/images/icArrLeftWhite@3x.png
  client/js/assets/images/icChevronDownWhite.png
  client/js/assets/images/icChevronDownWhite@2x.png
  client/js/assets/images/icChevronDownWhite@3x.png
  client/js/components/ButtonFilter/ButtonFilter.js
  client/js/components/ButtonFilter/index.js
  client/js/components/ButtonFilter/styles.js
  client/js/components/CardEvent/CardEvent.js
  client/js/components/CardEvent/index.js
  client/js/components/CardEvent/styles.js
  client/js/components/DatePicker/DatePicker.js
  client/js/components/DatePicker/index.js
  client/js/components/DatePicker/styles.js
  client/js/components/ModalOverlay/ModalOverlay.js
  client/js/components/SortActionSheet/SortActionSheet.js
  client/js/components/SortActionSheet/index.js
  client/js/components/SortActionSheet/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/EventCategory/EventCategory.js
  client/js/screens/EventCategory/EventCategoryContainer.js
  client/js/screens/EventCategory/index.js
  client/js/screens/EventCategory/styles.js
  client/js/screens/Home/Home.js
  client/js/screens/Home/HomeContainer.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#109 Create no data event screen in Saved screen
  client/js/App.js
  client/js/assets/images/icDiscoverMore.png
  client/js/assets/images/icDiscoverMore@2x.png
  client/js/assets/images/icDiscoverMore@3x.png
  client/js/assets/images/icFaveCircleActive.png
  client/js/assets/images/icFaveCircleActive@2x.png
  client/js/assets/images/icFaveCircleActive@3x.png
  client/js/components/ButtonDefault/ButtonDefault.js
  client/js/components/CardEvent/CardEvent.js
  client/js/components/CardEventSmall/CardEventSmall.js
  client/js/config/models.js
  client/js/context/SaveEventContext.js
  client/js/screens/Home/Home.js
  client/js/screens/Home/HomeContainer.js
  client/js/screens/Saved/Saved.js
  client/js/screens/Saved/SavedContainer.js
  client/js/screens/Saved/SavedStack.js
  client/js/screens/Saved/TabEvent/TabEvent.js
  client/js/screens/Saved/TabEvent/TabEventContainer.js
  client/js/screens/Saved/TabEvent/index.js
  client/js/screens/Saved/TabEvent/styles.js
  client/js/screens/Saved/TabSelfGuidedTour/TabSelfGuidedTour.js
  client/js/screens/Saved/TabSelfGuidedTour/TabSelfGuidedTourContainer.js
  client/js/screens/Saved/TabSelfGuidedTour/index.js
  client/js/screens/Saved/TabSelfGuidedTour/styles.js
  client/js/screens/Saved/index.js
  client/js/screens/Saved/styles.js
Labels: enhancement

#111 Single Self Guided Tour Screen
  client/js/assets/images/icFilterAudio.png
  client/js/assets/images/icFilterAudio@2x.png
  client/js/assets/images/icFilterAudio@3x.png
  client/js/assets/images/icFilterDistance.png
  client/js/assets/images/icFilterDistance@2x.png
  client/js/assets/images/icFilterDistance@3x.png
  client/js/assets/images/icFilterDuration.png
  client/js/assets/images/icFilterDuration@2x.png
  client/js/assets/images/icFilterDuration@3x.png
  client/js/assets/images/icFilterPetFriendly.png
  client/js/assets/images/icFilterPetFriendly@2x.png
  client/js/assets/images/icFilterPetFriendly@3x.png
  client/js/navigation/NavigationLayout.js
  client/js/screens/SelfGuidedTour/SelfGuidedTourContainer.js
  client/js/screens/SingleSelfGuided/SingleSelfGuided.js
  client/js/screens/SingleSelfGuided/SingleSelfGuidedContainer.js
  client/js/screens/SingleSelfGuided/index.js
  client/js/screens/SingleSelfGuided/styles.js
Labels: enhancement

#114 Save Selfguided Tours
  client/js/components/SelfGuidedItem/SelfGuidedItem.js
  client/js/screens/Saved/TabEvent/TabEvent.js
  client/js/screens/Saved/TabSelfGuidedTour/TabSelfGuidedTour.js
  client/js/screens/Saved/TabSelfGuidedTour/TabSelfGuidedTourContainer.js
  client/js/screens/Saved/TabSelfGuidedTour/styles.js
  client/js/screens/SingleSelfGuided/SingleSelfGuided.js
Labels: enhancement

#115 Connect data to StoryTrail with the logic
  client/js/assets/images/mediaControllers/icAudioPauseSmall.png
  client/js/assets/images/mediaControllers/icAudioPauseSmall@2x.png
  client/js/assets/images/mediaControllers/icAudioPauseSmall@3x.png
  client/js/components/AudioItem/AudioItem.js
  client/js/components/AudioItem/styles.js
  client/js/screens/SingleSelfGuided/SingleSelfGuided.js
  client/js/screens/StoryTrail/StoryTrail.js
  client/js/screens/StoryTrail/StoryTrailContainer.js
Labels: Epic, documentation

#116 bugfix - remove safe area view, update envent screen
  client/ios/Podfile.lock
  client/js/components/RatingScore/RatingScore.js
  client/js/screens/Booking/Booking.js
  client/js/screens/Booking/styles.js
  client/js/screens/Event/Event.js
  client/js/screens/Event/styles.js
  client/js/screens/Search/Search.js
  client/js/screens/Search/styles.js
Labels: bug, enhancement

#117 Mw feature submitreview
  client/js/apollo/mutations.js
  client/js/assets/images/icRatingBigStarFilled.png
  client/js/assets/images/icRatingBigStarFilled@2x.png
  client/js/assets/images/icRatingBigStarFilled@3x.png
  client/js/assets/images/icRatingBigStarOutline.png
  client/js/assets/images/icRatingBigStarOutline@2x.png
  client/js/assets/images/icRatingBigStarOutline@3x.png
  client/js/components/ReviewInput/ReviewInput.js
  client/js/components/ReviewInput/index.js
  client/js/components/ReviewScore/ReviewScore.js
  client/js/components/ReviewScore/index.js
  client/js/components/ReviewScore/styles.js
  client/js/components/Reviews/Reviews.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/Event/styles.js
  client/js/screens/SubmitReview/SubmitReview.js
  client/js/screens/SubmitReview/SubmitReviewContainer.js
  client/js/screens/SubmitReview/index.js
  client/js/screens/SubmitReview/styles.js
Labels: enhancement

#124 Fix bugs from merge conflict
  client/js/screens/Event/Event.js
  client/js/screens/Event/styles.js
  client/js/screens/SubmitReview/SubmitReview.js
Labels: bug

#122 Add features on Profile screen
  client/js/assets/images/icArrRightSmallDefault.png
  client/js/assets/images/icArrRightSmallDefault@2x.png
  client/js/assets/images/icArrRightSmallDefault@3x.png
  client/js/assets/images/icPrizeDefault.png
  client/js/assets/images/icPrizeDefault@2x.png
  client/js/assets/images/icPrizeDefault@3x.png
  client/js/components/ProfileMenu/ProfileMenu.js
  client/js/components/ProfileMenu/index.js
  client/js/components/ProfileMenu/styles.js
  client/js/screens/Home/Home.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/Profile/styles.js
Labels: enhancement

#126 Add Contact Host Screen
  client/js/navigation/NavigationLayout.js
  client/js/screens/ContactHost/ContactHost.js
  client/js/screens/ContactHost/ContactHostContainer.js
  client/js/screens/ContactHost/index.js
  client/js/screens/ContactHost/styles.js
  client/js/screens/Event/Event.js
Labels: enhancement

#127 Thank You page for host review
  client/ios/Podfile.lock
  client/js/navigation/NavigationLayout.js
  client/js/screens/ContactHost/ContactHost.js
  client/js/screens/Event/styles.js
  client/js/screens/SubmitReview/SubmitReview.js
  client/js/screens/ThankYouHost/ThankYouHost.js
  client/js/screens/ThankYouHost/ThankYouHostContainer.js
  client/js/screens/ThankYouHost/index.js
  client/js/screens/ThankYouHost/styles.js
  client/js/screens/ThankYouReview/ThankYouReview.js
  client/js/screens/ThankYouReview/ThankYouReviewContainer.js
  client/js/screens/ThankYouReview/index.js
  client/js/screens/ThankYouReview/styles.js
Labels: enhancement

#128 Add review features
  client/js/components/Reviews/Reviews.js
  client/js/components/Reviews/styles.js
  client/js/screens/Event/Event.js
  client/js/screens/Event/styles.js
Labels: enhancement

#123 Fixed style to self guided tour to fit the Designs
  client/js/components/SelfGuidedItem/SelfGuidedItem.js
  client/js/components/SelfGuidedItem/styles.js
  client/js/screens/SelfGuidedTour/SelfGuidedTour.js
  client/js/screens/SelfGuidedTour/styles.js
Labels: bug

#132 Add feature event map feature
  .gitignore
  client/js/screens/Event/Event.js
  client/js/screens/Event/EventContainer.js
Labels: enhancement

#134 Clean Up Code
  client/ios/Podfile.lock
  client/js/screens/Booking/Booking.js
  client/js/screens/Faq/FaqContainer.js
  client/js/screens/Search/Search.js
  client/yarn.lock
Labels: bug

#135 Add scrollview to contact host screen
  client/js/screens/ContactHost/ContactHost.js
Labels: bug

#138 Update styles
  client/js/components/TextWithIcon/TextWithIcon.js
  client/js/components/TextWithIcon/index.js
  client/js/components/TextWithIcon/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/Booking/PastEvents/PastEvents.js
  client/js/screens/Booking/PastEvents/styles.js
  client/js/screens/Booking/Upcoming/Upcoming.js
  client/js/screens/Booking/Upcoming/styles.js
  client/js/screens/Event/Event.js
  client/js/screens/Event/styles.js
  client/js/screens/EventCategory/EventCategory.js
  client/js/screens/EventCategory/styles.js
  client/js/screens/Home/Home.js
  client/js/screens/Profile/Profile.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SingleSelfGuided/SingleSelfGuided.js
  client/js/screens/SingleSelfGuided/styles.js
  client/yarn.lock
Labels: bug

#139 Update ReadMe
  README.md
  client/yarn.lock
Labels: documentation
